name: Publish to MCP Registry

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            copyleftdev/fabric-atelier:${{ steps.version.outputs.VERSION }}
            copyleftdev/fabric-atelier:latest
          labels: |
            io.modelcontextprotocol.server.name=io.github.copyleftdev/fabric-atelier
            org.opencontainers.image.title=Fabric Atelier
            org.opencontainers.image.description=AI-powered content processing with 226 Fabric patterns
            org.opencontainers.image.version=${{ steps.version.outputs.VERSION }}
            org.opencontainers.image.authors=copyleftdev
            org.opencontainers.image.url=https://github.com/copyleftdev/fabric-atelier
            org.opencontainers.image.source=https://github.com/copyleftdev/fabric-atelier
            org.opencontainers.image.licenses=MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  publish-registry:
    needs: publish-docker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/download/latest/mcp-publisher_linux_amd64.tar.gz" | tar xz
          sudo mv mcp-publisher /usr/local/bin/
          mcp-publisher --version
      
      - name: Extract version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi
      
      - name: Update server.json version
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          jq --arg version "$VERSION" \
            '.version = $version | .packages[0].version = $version' \
            server.json > server.json.tmp
          mv server.json.tmp server.json
          cat server.json
      
      - name: Validate server.json
        run: |
          npm install -g ajv-cli
          ajv validate \
            -s https://static.modelcontextprotocol.io/schemas/2025-09-29/server.schema.json \
            -d server.json
      
      - name: Publish to MCP Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mcp-publisher auth github --token $GITHUB_TOKEN
          mcp-publisher publish --verbose
      
      - name: Verify publication
        run: |
          sleep 10
          mcp-publisher status io.github.copyleftdev/fabric-atelier
